// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fopbzmyxckgkwhdnnspr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvcGJ6bXl4Y2tna3doZG5uc3ByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMzAzNzMsImV4cCI6MjA3MjcwNjM3M30.aI9-QYM95_Fd5x7Ri3RXzRRvV-Cog5X9P22g4t9f-VY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});